version: "3"
services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: ofc
      POSTGRES_USER: ofc
      POSTGRES_PASSWORD: ofc
    ports:
    - "5432:5432"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data